# Generated by Django 2.2.17 on 2020-12-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20201216_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='authapp/users_avatars'),
        ),
    ]
