# Generated by Django 2.2.17 on 2021-01-16 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210116_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 10, 17, 46, 784652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
