# Generated by Django 2.2.17 on 2021-01-16 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210116_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key_expired',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 11, 1, 7, 979384, tzinfo=utc)),
        ),
    ]
